### ISSUE TITLE
Review Latest Software Version

### ISSUE THREAD

**Issue by PickleRick271** [PickleRick271/Prototyping-Skills-and-Design-Challenge#14]
Hi Dr. Palmeri, 

Can you please review V2 of the Arduino software? I would appreciate any and all feedback!

For reference, title is ProtChallv2

Thanks!

**Comment by mlp6** [comment]
One significant issue is going to be the use of delays statements... right now, the `look_for_input()` calls are going to delay execution of the loop by 1 s each time that function is called.  This will be especially problematic in the flashing mode, and also when taking action on a button press as it sits and waits for a while.

I'm not following why you have some many nested statements; as I mentioned in class, I would strongly recommend using the interrupt approach to the button detection, but if you can motivate why you need this nested conditional sequence, I'm interested to hear your thought process.

**Comment by PickleRick271** [comment]
The way I thought it through when I did V1 in October, I figured that a relatively easy way to indicate each modality was to press the button and keep it pressed for a specific time. Pressing for one second but less than two would select the first mode, more than one and less than two would select the second mode, and so on. I believe the order I have at the moment is low, medium, high, blink, off. The delays were to make it more friendly to the user when executing the action of pressing for an easy-to-remember amount of time. 

I hope this makes sense, and that is the logic behind why I structured it that way with the delays and nested conditional sequence. I'm not sure if there is a more logical and easier way though than this.

**Comment by mlp6** [comment]
I still have a concern surrounding operation and absolutely timing though... But you can approach it this way and change the code if needed after some testing.

**Comment by mlp6** [comment]
You are correct that the interrupt approach will not work with the "held duration" approach for operation... that is actually a trickier approach to implement.  The envisioned approach was to simply cycle through the different modes with discrete button presses, but I don't want to derail your approach.  I just give the caution that I think it might be difficult to get working as you would like to.
